name: arifu_leafcheck
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^0.8.5+3
  flutter_spinkit: ^5.2.1
  dio: ^5.7.0
  flutter_tflite: ^1.0.1
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.2.1
  url_launcher: ^6.3.0 # Check for the latest version

  # Updated dependencies for TensorFlow Lite and image processing
  tflite_flutter: ^0.11.0
  image: ^3.3.0 # Added for image processing

dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  material_color_utilities: ^0.12.0
  string_scanner: ^1.3.0
  test_api: ^0.7.3
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/model_unquant.tflite
    - assets/model2_unquant.tflite
    - assets/labels.txt
